[theme]
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#1f1f1f"
secondaryBackgroundColor = "#1f1f1f"
textColor = "#ffffff"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[ui]
hideTopBar = false

[client]
showSidebarNavigation = true