[server]
# Enable XSRF protection
enableXsrfProtection = false

# Enable CORS handling
enableCORS = false

# Port configuration
port = 8501

# Address to bind to
address = "0.0.0.0"

# Disable usage stats
gatherUsageStats = false

[browser]
# Disable automatic browser opening
serverAddress = "0.0.0.0"

[theme]
# Dark theme matching Guinness branding
base = "dark"
primaryColor = "#C8102E"
backgroundColor = "#1f1f1f"
secondaryBackgroundColor = "#2a2a2a"
textColor = "#ffffff"

[client]
# Show error details
showErrorDetails = true
EOF < /dev/null